PR対応・スロットリング設定追加等
EC-CUBE/TwoFactorAuthCustomer42 pull request #4
Opened 2023-03-05 08:25 UTC by KenTanaka

2023-03-13 09:00 UTC, kiy0taka requested changes

2023-03-13 09:00 UTC, kiy0taka commented on Controller/TwoFactorAuthCustomerController.php
> +                    if($Customer->getDeviceAuthedPhoneNumber() === $phoneNumber) {
同じ会員で認証済みになっているかではなく、他の会員でも同じ番号によって認証済みになってないかの確認が必要かと思います。

2023-03-13 09:00 UTC, kiy0taka commented on Entity/TwoFactorAuthConfig.php
> +            $routes = array_splice($routes, array_search($route, $routes, true), 1);
`array_splice` の戻り値を `$routes` に再代入するのは意図した処理にならないかと思います。
https://www.php.net/manual/ja/function.array-splice.php#refsect1-function.array-splice-returnvalues

2023-03-13 09:00 UTC, kiy0taka commented on Entity/TwoFactorAuthType.php
> +     * @ORM\Column(name="name", type="string", nullable=true, length=200, unique=true)
理由がなければnot nullでいいかとお思いますが、nullを許可している理由はなんでしょうか？

2023-03-13 09:00 UTC, kiy0taka commented on Service/CustomerTwoFactorAuthService.php
> +    public const DEFAULT_EXPIRE_TIME = 3600;
services.yamlでも定義して、こちらでも定義している意図はなんでしょうか？

2023-03-15 11:19 UTC, KenTanaka commented on Service/CustomerTwoFactorAuthService.php
> +    public const DEFAULT_EXPIRE_TIME = 3600;
@kiy0taka 
services.yamlに設定されているが前提ですので、不要です。
削除しました。

2023-03-15 11:49 UTC, KenTanaka commented on Controller/TwoFactorAuthCustomerController.php
> +                    if($Customer->getDeviceAuthedPhoneNumber() === $phoneNumber) {
@kiy0taka 
指摘通りですので、以下の検索でチェックするように修正しました。

`$this->customerRepository->findOneBy(['device_authed_phone_number' => $phoneNumber])`

2023-03-15 12:47 UTC, KenTanaka commented on Entity/TwoFactorAuthConfig.php
> +            $routes = array_splice($routes, array_search($route, $routes, true), 1);
別レビューにて指摘頂いておりますので修正しました。

2023-03-15 12:47 UTC, KenTanaka commented on Entity/TwoFactorAuthType.php
> +     * @ORM\Column(name="name", type="string", nullable=true, length=200, unique=true)
別レビューにて指摘頂いておりますので修正しました。

2023-03-21 23:36 UTC, closed without merging