レビュー用PR_2023_03_24に関しての修正
EC-CUBE/TwoFactorAuthCustomer42 pull request #42
Opened 2023-03-24 11:00 UTC by sai-gillingham

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/3#discussion_r1147157803
について、他の->findOneBy([〇〇]) === null箇所の代わりにcount関数を利用するように更新しました。

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/3#discussion_r1147164107
について、本人確認認証のワンタイムトークン長をservices.ymlで変更出来るようになりました。

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/3#discussion_r1147172574
について、getFromPhonenumber/setFromPhonenumber関数名をgetFromPhoneNumber / setFromPhoneNumber になりました。

2023-03-27 09:13 UTC, kiy0taka requested changes

2023-03-27 09:13 UTC, kiy0taka commented on Service/CustomerTwoFactorAuthService.php
>      public function generateOneTimeTokenValue(?int $tokenLengthOverride = null): string
`$tokenLengthOverride` は削除お願いします。メソッド呼び出しで変更するユースケースはないかと思います。

2023-03-27 11:39 UTC, sai-gillingham commented on Service/CustomerTwoFactorAuthService.php
>      public function generateOneTimeTokenValue(?int $tokenLengthOverride = null): string
レビューして頂いてありがとうございます。

こちらの件について少しご相談したいことがあります。

実は二段階認証（SMS）プラグインがそのパラメータを利用しています。

https://github.com/sai-gillingham/TwoFactorAuthCustomerSms42/blob/eebcc7e239f79fab55041874ad6950eff26747a3/Controller/TwoFactorAuthCustomerSmsController.php#L186-L188

```php
        $token = $this->customerTwoFactorAuthService->generateOneTimeTokenValue(
            (int) $this->eccubeConfig->get('plugin_eccube_2fa_sms_one_time_token_length')
        );
```

こちらのコードを作った時に本会員時の本人認証のワンタイムトークン長と二段階認証のワンタイムトークン長の設定を別けるユーズーケースがあるかとおもいました。

こちらの対応についてどちらの方向で宜しいでしょうか？

① 本会員時の本人認証のワンタイムトークン長設定と二段階認証のワンタイムトークン長設定をまとめること
② 二段階認証（SMS）プラグインでgenerateOneTimeTokenValueに似ている新しい関数を作成すること

2023-03-29 00:30 UTC, kiy0taka commented on Service/CustomerTwoFactorAuthService.php
>      public function generateOneTimeTokenValue(?int $tokenLengthOverride = null): string
@sai-gillingham SMS認証で利用するトークンの長さという限定された用途なので、プラグイン毎に異なるものを使うより1つにまとめておいた方がいいと思うので、オーバーライドはなしで行きましょう。`generateExpiryDate`の方も同様かと思いますので対応お願いします。

2023-03-29 00:45 UTC, KenTanaka commented on Service/CustomerTwoFactorAuthService.php
>      public function generateOneTimeTokenValue(?int $tokenLengthOverride = null): string
@kiy0taka 了解です。

2023-03-29 02:01 UTC, sai-gillingham commented on Service/CustomerTwoFactorAuthService.php
>      public function generateOneTimeTokenValue(?int $tokenLengthOverride = null): string
@kiy0taka 
回答ありがとうございます。
SMSトークンの長さのオーバーライドパラメータとSMS有効期限のオーバーライドパラメータを消しました。

オーバーライドパラメータを消したので、SMSプラグインのトークンの長さ設定とSMS有効期限設定は不要になったため、その設定を消しましたので、ご確認お願いいたします。
https://github.com/EC-CUBE/TwoFactorAuthCustomerSms42/pull/15/files

2023-03-29 05:48 UTC, kiy0taka approved these changes

2023-03-29 05:48 UTC, merged